// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 9324fb97fb5b84229a680523f9fa7a3779696fe8baade57025b04a410e4e3c07
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[BuilderPreferencesEntry](`ssz-static:"false"`)

// MarshalSSZ marshals the *BuilderPreferencesEntry to SSZ-encoded bytes.
func (t *BuilderPreferencesEntry) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BuilderPreferencesEntry to SSZ-encoded bytes, appending to the provided buffer.
func (t *BuilderPreferencesEntry) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BuilderPreferencesEntry)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ProposerPubkey'
		dst = append(dst, t.ProposerPubkey[:48]...)
	}
	// Offset Field #1 'URL'
	// Offset Field #2 'Auth'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #3 'MaxExecutionPayment'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.MaxExecutionPayment))
	}
	{ // Dynamic Field #1 'URL'
		binary.LittleEndian.PutUint32(dst[dstlen+48:], uint32(len(dst)-dstlen))
		vlen := len(t.URL)
		if vlen > 2048 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2048), "URL")
		}
		dst = append(dst, t.URL[:]...)
	}
	{ // Dynamic Field #2 'Auth'
		binary.LittleEndian.PutUint32(dst[dstlen+52:], uint32(len(dst)-dstlen))
		t := t.Auth
		if t == nil {
			t = new(SignedBuilderRequestAuth)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Auth")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BuilderPreferencesEntry from SSZ-encoded bytes.
func (t *BuilderPreferencesEntry) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 64 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 64)
	}
	{ // Field #0 'ProposerPubkey' (static)
		buf := buf[0:48]
		copy(t.ProposerPubkey[:], buf)
	}
	// Field #1 'URL' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[48:52]))
	if offset1 != 64 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 64), "URL:o")
	}
	// Field #2 'Auth' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[52:56]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "Auth:o")
	}
	{ // Field #3 'MaxExecutionPayment' (static)
		buf := buf[56:64]
		t.MaxExecutionPayment = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'URL' (dynamic)
		buf := buf[offset1:offset2]
		if len(buf) > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), 2048), "URL")
		}
		t.URL = sszutils.ExpandSlice(t.URL, len(buf))
		copy(t.URL[:], buf)
	}
	{ // Field #2 'Auth' (dynamic)
		buf := buf[offset2:]
		if t.Auth == nil {
			t.Auth = new(SignedBuilderRequestAuth)
		}
		if err = t.Auth.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Auth")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BuilderPreferencesEntry.
func (t *BuilderPreferencesEntry) SizeSSZ() (size int) {
	if t == nil {
		t = new(BuilderPreferencesEntry)
	}
	// Field #0 'ProposerPubkey' static (48 bytes)
	// Field #1 'URL' offset (4 bytes)
	// Field #2 'Auth' offset (4 bytes)
	// Field #3 'MaxExecutionPayment' static (8 bytes)
	size += 64
	{ // Dynamic field #1 'URL'
		size += len(t.URL)
	}
	{ // Dynamic field #2 'Auth'
		size += t.Auth.SizeSSZ()
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *BuilderPreferencesEntry.
func (t *BuilderPreferencesEntry) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BuilderPreferencesEntry using the given hash walker.
func (t *BuilderPreferencesEntry) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BuilderPreferencesEntry)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ProposerPubkey'
		hh.PutBytes(t.ProposerPubkey[:48])
	}
	{ // Field #1 'URL'
		vlen := uint64(len(t.URL))
		if vlen > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2048), "URL")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.URL[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(2048, vlen, 1))
	}
	{ // Field #2 'Auth'
		t := t.Auth
		if t == nil {
			t = new(SignedBuilderRequestAuth)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Auth")
		}
	}
	{ // Field #3 'MaxExecutionPayment'
		hh.PutUint64(uint64(t.MaxExecutionPayment))
	}
	hh.MerkleizeProgressiveWithActiveFields(idx, []byte{0x0f})
	return nil
}
