// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: b79ae8cfa942163686679757412dcad98eb2d4d7652e98178d49070b42493362
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"github.com/attestantio/go-eth2-client/spec/gloas"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[PayloadAttestationMessages](`ssz-static:"false"`)

// MarshalSSZ marshals the *PayloadAttestationMessages to SSZ-encoded bytes.
func (t *PayloadAttestationMessages) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *PayloadAttestationMessages to SSZ-encoded bytes, appending to the provided buffer.
func (t *PayloadAttestationMessages) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(PayloadAttestationMessages)
	}
	vlen := len(*t)
	if vlen > 512 {
		return nil, sszutils.ErrListLengthFn(vlen, 512)
	}
	for idx1 := range vlen {
		t := (*t)[idx1]
		if t == nil {
			t = new(gloas.PayloadAttestationMessage)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPathf(err, "[%d]", idx1)
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *PayloadAttestationMessages from SSZ-encoded bytes.
func (t *PayloadAttestationMessages) UnmarshalSSZ(buf []byte) (err error) {
	itemCount := len(buf) / 146
	if len(buf)%146 != 0 {
		return sszutils.ErrListNotAlignedFn(len(buf), 146)
	}
	if itemCount > 512 {
		return sszutils.ErrListLengthFn(itemCount, 512)
	}
	*t = sszutils.ExpandSlice(*t, itemCount)
	for idx1 := range itemCount {
		if (*t)[idx1] == nil {
			(*t)[idx1] = new(gloas.PayloadAttestationMessage)
		}
		buf := buf[146*idx1 : 146*(idx1+1)]
		if err = (*t)[idx1].UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPathf(err, "[%d]", idx1)
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *PayloadAttestationMessages.
func (t *PayloadAttestationMessages) SizeSSZ() (size int) {
	if t == nil {
		t = new(PayloadAttestationMessages)
	}
	size += len(*t) * 146
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *PayloadAttestationMessages.
func (t *PayloadAttestationMessages) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *PayloadAttestationMessages using the given hash walker.
func (t *PayloadAttestationMessages) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(PayloadAttestationMessages)
	}
	vlen := uint64(len(*t))
	if vlen > 512 {
		return sszutils.ErrListLengthFn(vlen, 512)
	}
	idx := hh.StartTree(sszutils.TreeTypeBinary)
	for idx1 := range int(vlen) {
		t := (*t)[idx1]
		if t == nil {
			t = new(gloas.PayloadAttestationMessage)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPathf(err, "[%d]", idx1)
		}
		if (idx1+1)%256 == 0 {
			hh.Collapse()
		}
	}
	hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(512, vlen, 32))
	return nil
}
