// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: fb4d852249d3d96e0adc4554948977bb95082132ce5dac827fe63e7971261cb4
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package gloas

import (
	"github.com/attestantio/go-eth2-client/spec/gloas"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[SignedProposerPreferencesList](`ssz-static:"false"`)

// MarshalSSZ marshals the *SignedProposerPreferencesList to SSZ-encoded bytes.
func (t *SignedProposerPreferencesList) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *SignedProposerPreferencesList to SSZ-encoded bytes, appending to the provided buffer.
func (t *SignedProposerPreferencesList) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedProposerPreferencesList)
	}
	vlen := len(*t)
	if vlen > 64 {
		return nil, sszutils.ErrListLengthFn(vlen, 64)
	}
	for idx1 := range vlen {
		t := (*t)[idx1]
		if t == nil {
			t = new(gloas.SignedProposerPreferences)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPathf(err, "[%d]", idx1)
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *SignedProposerPreferencesList from SSZ-encoded bytes.
func (t *SignedProposerPreferencesList) UnmarshalSSZ(buf []byte) (err error) {
	itemCount := len(buf) / 172
	if len(buf)%172 != 0 {
		return sszutils.ErrListNotAlignedFn(len(buf), 172)
	}
	if itemCount > 64 {
		return sszutils.ErrListLengthFn(itemCount, 64)
	}
	*t = sszutils.ExpandSlice(*t, itemCount)
	for idx1 := range itemCount {
		if (*t)[idx1] == nil {
			(*t)[idx1] = new(gloas.SignedProposerPreferences)
		}
		buf := buf[172*idx1 : 172*(idx1+1)]
		if err = (*t)[idx1].UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPathf(err, "[%d]", idx1)
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *SignedProposerPreferencesList.
func (t *SignedProposerPreferencesList) SizeSSZ() (size int) {
	if t == nil {
		t = new(SignedProposerPreferencesList)
	}
	size += len(*t) * 172
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *SignedProposerPreferencesList.
func (t *SignedProposerPreferencesList) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *SignedProposerPreferencesList using the given hash walker.
func (t *SignedProposerPreferencesList) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedProposerPreferencesList)
	}
	vlen := uint64(len(*t))
	if vlen > 64 {
		return sszutils.ErrListLengthFn(vlen, 64)
	}
	idx := hh.StartTree(sszutils.TreeTypeBinary)
	for idx1 := range int(vlen) {
		t := (*t)[idx1]
		if t == nil {
			t = new(gloas.SignedProposerPreferences)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPathf(err, "[%d]", idx1)
		}
		if (idx1+1)%256 == 0 {
			hh.Collapse()
		}
	}
	hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(64, vlen, 32))
	return nil
}
